framework:
    asset_mapper:
        paths:
            - '%kernel.project_dir%/assets'
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
