security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            entry_point: App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: /login
            access_denied_url: /login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/assignments/\d+/suggest-modification-form, roles: ROLE_USER }
        - { path: ^/assignment/add, roles: [ROLE_DELEGATE, ROLE_ADMIN] }
        - { path: ^/assignments/\d+/edit, roles: [ROLE_DELEGATE, ROLE_ADMIN] }
        - { path: ^/assignment/\d+/delete, roles: [ROLE_DELEGATE, ROLE_ADMIN] }
        - { path: ^/assignments/manage, roles: [ROLE_DELEGATE, ROLE_ADMIN] }
        - { path: ^/, roles: ROLE_USER }
